server.port=8081

# Keycloak Configuration
keycloak.auth-server-url=http://localhost:8180
keycloak.realm=cookieclicker
keycloak.client-id=cookieclicker-client
keycloak.client-secret=mkQJKiaMKsgNxkO2E3TUYflTbDvt6EMP

# Keycloak Admin Credentials (for user registration)
keycloak.admin-username=admin
keycloak.admin-password=admin

# JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/cookieclicker
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/cookieclicker/protocol/openid-connect/certs

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.at.spengergasse=DEBUG

