spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: game-service-rest
          uri: lb://game-service
          predicates:
            - Path=/api/rooms/**
        - id: game-service-ws
          uri: lb://game-service
          predicates:
            - Path=/ws/**
        - id: persistance-service
          uri: lb://persistance-service
          predicates:
            - Path=/api/stats/**

server:
  port: ${GATEWAY_PORT:8090}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
